### PR TITLE
Release 0.10.1

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Comment by blink1073** [comment]
@conda-forge-admin, please rerender.

**Comment by blink1073** [comment]
@SylvainCorlay, I'm getting an error due to the recent 4.2.3 zeromq package:

`libzmq.so.5.1.1: cannot open shared object file: No such file or directory`

**Comment by blink1073** [comment]
Pinning to 4.2.1 fixes the build.

**Comment by SylvainCorlay** [comment]
Checking this out as soon as I get by a keyboard.

**Comment by SylvainCorlay** [comment]
From what I see on my phone, pyzmq is built assuming 4.2.1 but the conda package requires 4.2.*.

**Comment by blink1073** [comment]
Which conda package is requiring 4.2.*?

**Comment by blink1073** [comment]
Ah, I see: https://github.com/conda-forge/pyzmq-feedstock/blob/master/recipe/meta.yaml#L26

**Comment by SylvainCorlay** [comment]
Yes there is a build time thing in pyzmq which makes it link with a specific suffix for the  .so. i need to check this on a rral screen :)

**Comment by SylvainCorlay** [comment]
This looks good to me as a workaround in the mean time.

**Comment by blink1073** [comment]
I'm wary of having an explicit version pin like that for a runtime requirement, is that truly the case?

**Comment by SylvainCorlay** [comment]
cc @minrk: do you know why `pyzmq` looks for `libzmq.so.4.2.1` specifically?

**Comment by SylvainCorlay** [comment]
The pyzmq documentation specifies

_Supported LibZMQ
PyZMQ aims to support all stable ( ≥2.1.4, ≥ 3.2.2, ≥ 4.0.1 ) and active development ( ≥ 4.2.0 ) versions of libzmq. Building the same pyzmq against various versions of libzmq is supported, but only the functionality of the linked libzmq will be available._

**Comment by blink1073** [comment]
Happy to have the version pin in `pyzmq`, I didn't want to have it here :wink:.

**Comment by blink1073** [comment]
Hmm, no bueno: `ImportError: libzmq.so.5.1.1: cannot open shared object file: No such file or directory`

**Comment by SylvainCorlay** [comment]
@blink1073 cf https://github.com/conda-forge/pyzmq-feedstock/issues/27

If you know a conda-forge master who has privileges to remove / tag packages on the channel, it is the time to get their attention 😄

**Comment by SylvainCorlay** [comment]
👍

**Comment by minrk** [comment]
Identified it: it's a bug caused by using CMake to build libzmq, which we shouldn't be doing. This will be fixed going forward by removing CMake from zeromq: https://github.com/conda-forge/zeromq-feedstock/pull/20. It's going to be a hard transition, because the zeromq builds have been creating the wrong versions since we started using CMake in 4.2.1. Fixing this on an existing will break any library that links libzmq that was built with cmake due to the bug, unless we create a symlink for the bad cmake-generated library to the right version in the fixed package.

**Pull request merged**
